---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-config
  namespace: kube-system
data:
  config: |
    <label @FLUENT_LOG>
      <match fluent.**>
       @type null
      </match> 
    </label>
    <source>
       @type tail
       @id in_tail_container_logs
       path /var/log/containers/*.log
       exclude_path ["/var/log/containers/omc.**"]
       pos_file /var/log/fluentd.log.pos
       path_key tailed_path
       tag pod.*
       read_from_head true
       refresh_interval 30
       <parse>
         @type json
       </parse>
    </source>
    <filter pod.**>
       @type record_transformer
       enable_ruby true
       <record>
        message   ${record.to_json}
        entityType omc_kubernetes_pod
        entityName "KubernetesPod"
        sourceName "PodLog"
        logEntity "${record['tailed_path']}"
       </record>
    </filter>
    <source>
       @type systemd
       tag kubelet
       path /run/log/journal
       matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
       read_from_head true

       <storage>
        @type local
        path /var/log/fluentd-journald-kubelet-cursor.json
       </storage>

       <entry>
        fields_strip_underscores true
        fields_lowercase true
       </entry>
    </source>
    <filter kubelet>
       @type record_transformer
       enable_ruby true
       <record>	
        message    ${record.to_json}
        entityType omc_kubernetes_cluster
        entityName "OKEFluentd"
        sourceName "KubeletLogs"
        logEntity "${record['tailed_path']}"
       </record>
    </filter>

    <match kubelet>
       @type oracle_omc_loganalytics                    
       omc_oauth_client_id           "#{ENV['OMC_CLIENTID']}"
       omc_oauth_client_secret       "#{ENV['OMC_SECRET']}"
       omc_oauth_username            "#{ENV['OMC_USER']}"
       omc_oauth_password            "#{ENV['OMC_PASSWORD']}"
       omc_oauth_scope               "#{ENV['OMC_SCOPE']}"
       omc_oauth_token_url           "#{ENV['OMC_TOKEN']}"
       omc_oauth_upload_url          "#{ENV['OMC_UPLOAD']}"
       <buffer tag>
            @type file
            path /var/log/fluentd/omckubeletbuffer
            overflow_action block
            disable_chunk_backup true
       </buffer>	
    </match>
    <match pod.**>
       @type oracle_omc_loganalytics                    
       omc_oauth_client_id           "#{ENV['OMC_CLIENTID']}"
       omc_oauth_client_secret       "#{ENV['OMC_SECRET']}"
       omc_oauth_username            "#{ENV['OMC_USER']}"
       omc_oauth_password            "#{ENV['OMC_PASSWORD']}"
       omc_oauth_scope               "#{ENV['OMC_SCOPE']}"
       omc_oauth_token_url           "#{ENV['OMC_TOKEN']}"
       omc_oauth_upload_url          "#{ENV['OMC_UPLOAD']}"
       <buffer tag>
            @type file
            path /var/log/fluentd/omcpodbuffer
            overflow_action block
            disable_chunk_backup true
       </buffer>
    </match>