---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-config
  namespace: kube-system
data:
  config: |
    <match fluent.**>
      @type null
    </match>
    <source>
       @type tail
       @id in_tail_container_logs
       path /var/log/containers/istio*.log
       #exclude_path ["/var/log/containers/envoy.**", "/var/log/containers/coredns.**"]
       pos_file /var/log/fluentd.log.pos
       tag istio.*
       read_from_head false
       refresh_interval 30
       <parse>
         @type json
         #time_format %Y-%m-%dT%H:%M:%S.%NZ
         #time_type string
       </parse>
    </source>
    <source>
       @type tail
       @id in_tail_productpage_logs
       path /var/log/containers/productpage*.log
       pos_file /var/log/productpage.log.pos
       tag productpage.*
       read_from_head false
       refresh_interval 30
       <parse>
         @type json
       </parse>
    </source>
    <source>
       @type systemd
       tag kubelet
       path /run/log/journal
       matches [{ "_SYSTEMD_UNIT": "kubelet.service" }]
       read_from_head true

       <storage>
        @type local
        path /var/log/fluentd-journald-kubelet-cursor.json
       </storage>

       <entry>
        fields_strip_underscores true
        fields_lowercase true
       </entry>
    </source>

    <match kubelet>
      @type http
      endpoint <omcurl>/serviceapi/data.storage/odu
      #ssl_no_verify true  # default: false
      http_method     post    # default: post
      #content_type    application/octet-stream
      headers {"X-USER-IDENTITY-DOMAIN-NAME":"<tenant>", "X-User-Defined-Properties": "filename:Kuberneteslogs,uploadName:KuberneteswithIstio,entityName:Kubelet,entityType:Kubernetes Cluster,logSourceName:KubeletLogs","Content-Type":"application/octet-stream"}
      <auth>
        method basic
        username <userid>
        password <password>
      </auth>
    </match>
    <match istio.**>
      @type http
      endpoint <omcurl>/serviceapi/data.storage/odu
      #ssl_no_verify true  # default: false
      http_method     post    # default: post
      headers {"X-USER-IDENTITY-DOMAIN-NAME":"<tenant>", "X-User-Defined-Properties": "filename:Kuberneteslogs,uploadName:KuberneteswithIstio,entityName:IstioLogs,entityType:Kubernetes Pod,logSourceName:IstioMixerLog","Content-Type":"application/octet-stream"}
      <auth>
        method basic
        username <userid>
        password <password>
      </auth>
      <buffer>
        @type memory
      </buffer>
    </match>
    <match productpage.**>
      @type http
      endpoint <omcurl>/serviceapi/data.storage/odu
      #ssl_no_verify true  # default: false
      http_method     post    # default: post
      #content_type    application/octet-stream
      headers {"X-USER-IDENTITY-DOMAIN-NAME":"<tenant>", "X-User-Defined-Properties": "filename:Kuberneteslogs,uploadName:KuberneteswithIstio,entityName:Productpage,entityType:Kubernetes Pod,logSourceName:ProductpagePODlogs","Content-Type":"application/octet-stream"}
      <auth>
        method basic
        username <userid>
        password <password>
      </auth>
    </match>