apiVersion: v1
kind: Secret
metadata:
  name: omcsecret
  namespace: kube-system
type: Opaque
data:
  username: 
  password: 
  oauthclientid: 
  oauthsecret:  
  oauthscope: 
  oauthtoken: 
  oauthupload: 